### ISSUE TITLE
エラー報告

### ISSUE THREAD

**Issue by Sakuraga200323** [yuttyann/ScriptEntityPlus#3]
サーバー起動時に以下のようなエラーが絶え間無く流れています。
Paperサーバーです。
**git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**

```
Could not pass event BlockPhysicsEvent to ScriptBlockPlus v2.1.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.World.a(World.java:595) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.World.applyPhysics(World.java:551) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.World.update(World.java:501) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.World.notifyAndUpdatePhysics(World.java:453) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:437) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.BlockDaylightDetector.c(BlockDaylightDetector.java:49) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.TileEntityLightDetector.e(SourceFile:16) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1658) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException: map-01 does not exist
        at com.github.yuttyann.scriptblockplus.utils.Utils.getWorld(Utils.java:165) ~[?:?]
        at com.github.yuttyann.scriptblockplus.BlockCoords.fromString(BlockCoords.java:309) ~[?:?]
        at com.github.yuttyann.scriptblockplus.file.json.builder.BlockCoordsAdapter.deserialize(BlockCoordsAdapter.java:45) ~[?:?]
        at com.github.yuttyann.scriptblockplus.file.json.builder.BlockCoordsAdapter.deserialize(BlockCoordsAdapter.java:34) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.github.yuttyann.scriptblockplus.file.json.BaseJson.loadJson(BaseJson.java:437) ~[?:?]
        at com.github.yuttyann.scriptblockplus.file.json.BaseJson.<init>(BaseJson.java:129) ~[?:?]
        at com.github.yuttyann.scriptblockplus.file.json.basic.OneJson.<init>(OneJson.java:81) ~[?:?]
        at com.github.yuttyann.scriptblockplus.file.json.derived.BlockScriptJson.<init>(BlockScriptJson.java:43) ~[?:?]
        at com.github.yuttyann.scriptblockplus.file.json.CacheJson.newInstance(CacheJson.java:78) ~[?:?]
        at com.github.yuttyann.scriptblockplus.file.json.BaseJson.newJson(BaseJson.java:154) ~[?:?]
        at com.github.yuttyann.scriptblockplus.file.json.derived.BlockScriptJson.get(BlockScriptJson.java:64) ~[?:?]
        at com.github.yuttyann.scriptblockplus.listener.BlockListener.onBlockPhysics(BlockListener.java:64) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor534.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 17 more
```

人が入るとパッタリ止むことが多いです。
ご確認のほどよろしくお願いします。

**Comment by yuttyann** [comment]
恐らくスレッド違いなので、ScriptBlockPlusの報告の場合はこちらの[issue](https://github.com/yuttyann/ScriptBlockPlus/issues)にお願いします。

ワールドが正常に読み込まれていないことが原因の様です。
バージョンが古いので最新のバージョンに更新してみてください。
(現在は v2.1.7までリリースされています。)
また、自動アップデート機能を有効にしていただければ常に最新の情報に更新することができます。

**しかし、現在1.12-1.12.2で正常にプラグインが読み込まれない不具合が発生しているので、修正を行った以下のプラグインをご利用ください。**
[プラグイン(解凍してください).zip](https://github.com/yuttyann/ScriptEntityPlus/files/7578843/default.zip)
